version: "3.9"
services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - "./files:/etc/nginx/files"
      - "./documents:/etc/nginx/documents"
    depends_on:
      - web
    ports:
      - "800:80"
    networks:
      - "web.network"
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      # - ".:/app"
      - "./documents:/app/documents"
    restart: "always"
    environment:
      - Replica= {{.Task.Name}}
    networks:
      - "web.network"
    deploy:
      replicas: 1
networks:
  web.network:

 
